### ISSUE TITLE
Support Comments in JSON configuration files

### ISSUE THREAD

**Issue by ltnd** [marklogic-community/ml-app-deployer#187]
Could it be possible for ml-gradle to allow comments in FasterXML parser (ALLOW_COMMENTS) so we can deactivate a config in a JSON file instead of having to delete the part ?
Example :
{
  "database-name" : "%%DATABASE%%",
  "range-element-index" : [ /*{
    "scalar-type" : "int",
    "namespace-uri" : null,
    "localname" : "id",
    "collation" : null,
    "range-value-positions" : false,
    "invalid-values" : "ignore"
  } */]
}

**Comment by rjrudin** [comment]
Yes, I'll try to include this 3.1.0, which will be released within a couple weeks or so.

**Comment by rjrudin** [comment]
Doing two things to support this:

1. Consolidating all instantiations of ObjectMapper into a static ObjectMapperFactory class which enables the Jackson "allow comments" feature
1. Modifying ManageClient so that it can optionally "clean" JSON payloads by reading them into a JsonNode and then writing them back out to a String, which ensures any comments that are ignored are then removed. 

Since there's a little cost to that "cleaning" of JSON, this behavior will be disabled by default. A new property - mlManageCleanJsonPayloads - will allow for the behavior to be enabled.
