### ISSUE TITLE
Load schemas from database-specific directory

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-app-deployer#308]
Consider adding support for loading schemas from ./databases/(name of database)/schemas/. 

This is a little debatable because currently, only resources are loaded from ./databases/(name of database), and a schema is not a resource per the Manage API.

**Comment by jonesyface** [comment]
I think the problem with using the (name of database) within the directory structure is that it means you're having to hardcode this value in your project rather than having it configurable via gradle.properties. This means for example the DB will have to have the same name across all environments when this may not be desirable/possible.

**Comment by rjrudin** [comment]
@jonesyface ml-app-deployer already supports this convention for a number of resources (not yet schemas), I haven't had any feedback about it being problematic due to database names changing across environments. I haven't heard of someone ever doing that - seems like it would cause a lot of confusion, not just in a deployment context.

**Comment by rjrudin** [comment]
Will need to account for previewing a deployment - i.e. how to disable this during a preview.
