### ISSUE TITLE
ScaffoldGenerator is missing some directories

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-app-deployer#343]
https://github.com/marklogic-community/ml-app-deployer/blob/master/src/main/java/com/marklogic/appdeployer/scaffold/ScaffoldGenerator.java#L21

After running mlNewProject with gradle 3.13.0, I received the following src structure
src/main/
- ml-config/ 
- ml-modules/

I expected:
src/main/
- ml-config/
- ml-data/
- ml-modules/
- ml-plugins/
- ml-schemas/

**Comment by prestonmcgowan** [comment]
Gradle 3.13.0 project structure: https://github.com/marklogic-community/ml-gradle/wiki/Project-layout

**Comment by rjrudin** [comment]
What OS, and does this work on the previous version of ml-gradle you were using (please identify if so)?

My initial thought is this is another bug in ml-gradle based on how Java 11 and the Gradle daemon work in resolving file references - that ScaffoldTask needs to be updated to do 'new File(".").getAbsolutePath()' instead of just ".".

**Comment by prestonmcgowan** [comment]
Mac 10.14.3
I hadn't looked for the ml-data, ml-plugins, ml-schemas directories before the 3.13.0 release since I don't believe these directories were supported.

The ScaffoldTask doesn't look like it supports the new 3.13.0 directories.

**Comment by rjrudin** [comment]
Ah I understand the intent now. ml-config and ml-modules are both created because there are files created under each of them. There aren't files to stub out under the 3 other directories, and I don't think empty directories should be made for the following reasons:

1. I expect MlcpTask to be used more often than ml-data is needed
1. System plugins are very rare
1. ml-schemas isn't the best location for schemas - ml-config/databases/(db name)/schemas is better
