### ISSUE TITLE
mlgradle DataDirectory properties do not work correctly with replica usage

### ISSUE THREAD

**Issue by markplotnick** [marklogic-community/ml-app-deployer#383]
Using either
```mlForestDataDirectory```
or
```mlDatabaseDataDirectories```
ml-gradle is only putting the replica forests into the designated directory, the primary forest is being created in the default data directory.

Example gradle property settings:

```
mlHost=somehost.demo.marklogic.com
mlUsername=admin
mlPassword=admin
mlAppName=lx
mlRestPort=8010

mlContentDatabaseName=lxdb
mlContentForestsPerHost=2
mlDatabaseNamesAndReplicaCounts=lxdb,1
mlForestDataDirectory=/space
```

the last **`mlForestDataDirectory`** property can be replaced with:
```
mlDatabaseDataDirectories=lxdb,/space
```
with the exact same results.

**Comment by markplotnick** [comment]
This occurs in ml-gradle version 3.16.0

**Comment by rjrudin** [comment]
My guess is you don't have a file under src/main/ml-config/databases with a database-name of "lxdb" in it. 

Because ml-app-deployer doesn't find such a file, it doesn't create a database before the call to /v1/rest-apis (it can't create a database it doesn't know about). Then when /v1/rest-apis is called - which happens because mlRestPort is set - that endpoint automatically creates a REST server, a content database, and a modules database. But the content database you get is not based on any properties. 

So the fix should be to just stub out a file in the "databases" directory. This will result in the properties being applied to the forests for "lxdb", which happens before the call to /v1/rest-apis.

I just did a test to verify that this is the fix, and it worked correctly. If that doesn't happen for you, please reopen.
