### ISSUE TITLE
Redeployment of amps does not work correctly

### ISSUE THREAD

**Issue by mnuman** [marklogic-community/ml-app-deployer#407]
HI,

We have done an update to an amp, adding an additional role. However, we cannot seem to successfully upload the new role into the environment: ml-gradle keeps on asserting that our amps has not changed - which is clearly incorrect.
I have looked into the Java code for the underlying ml-app-deployer and it seems to me that in https://github.com/marklogic-community/ml-app-deployer/blob/master/src/main/java/com/marklogic/appdeployer/command/security/DeployAmpsCommand.java you're not taking the roles into consideration:

![amp](https://user-images.githubusercontent.com/3323096/77189687-3ef5d580-6ad8-11ea-8533-ca627d0518cc.png)

**Comment by rjrudin** [comment]
Finally following up on this - set mlDeployAmpsWithCma=false. CMA does not allow for amp roles to be updated, which is why ml-app-deployer doesn't look at roles when determining whether the amp is unchanged or not. 

If you're not CMA, then /manage/v2/amps will be used, and updates will always be made.
